#This R script separates the merged E-prime data for a specific participant at a specific time point into 7 different data files for the 7 runs of 4 MRI tasks.  
#Created by Feng Gu in September 2019. Modified by Feng Gu in May 2020. 


############################## SETTING UP ##############################

args = commandArgs(trailingOnly=TRUE) #take user's input from the command line, when running this script in terminal. 

BEH_DIR <- "/home/cranilab/Documents/CRANI/Active_Studies/CogRehab/Data/MRI_data/fMRI_behavioral_data/" #create a variable BEH_DIR using the path of the behavioral data folder. 

id <- args[1] #take user's first input as ID (e.g., CR001)

TP <- args[2] #take user's second input as TP (e.g., 1)

merged <- read.delim(file.path(paste0(BEH_DIR, '/Merged/', id, "_TP", TP, '/merged_',id, "_TP", TP, '.txt')), stringsAsFactors=FALSE) #read merged data with the ID and TP information


############################## DATA CLEANING #############################

# Sometimes the output of E-merge has some extra rows before the actual data, to account for this: 

title <- which(merged[1]=="ExperimentName") # get the row number of the row where the first column is "ExperimentName"

# if there are extra rows: 
if(length(title)>0){
merged <- tail(merged, -((title-1))) # remove all the rows before the row where the first column is "ExperimentName" so that "ExperimentName" is in first row of first column

colnames(merged) <- as.character(unlist(merged[1,])) #rename columns using the first row of data 

merged <- tail(merged, -1) #remove first row.
}

############################## SUBSETTING & MORE CLEANING #################################

######## create a subset of run 1 of vm_encoding task
vm_run1 <- subset(merged, grepl(pattern = "^VM_encoding", merged$ExperimentName) & grepl(pattern = "1$", merged$ExperimentName))  #create a subset of Run 1 of encoding task (experiment name starts with VM_encoding and ends with 1)
vm_run1[vm_run1 == "NULL"] <- NA  #change all the "NULL" values to NA
vm_run1 <- vm_run1[, colSums(is.na(vm_run1)) != nrow(vm_run1)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime) 

#note: sometimes E-prime generates LongFixation1.OnsetTime instead of LongFixation.OnsetTime. To account for this: 
if(any(names(vm_run1) == "LongFixation1.OnsetTime")){
names(vm_run1)[names(vm_run1) == "LongFixation1.OnsetTime"] <- "LongFixation.OnsetTime"
}


######## create a subset of run 2 of vm_encoding task
vm_run2 <- subset(merged, grepl(pattern = "^VM_encoding", merged$ExperimentName) & grepl(pattern = "2$", merged$ExperimentName)) #create a subset of Run 2 of encoding task (experiment name starts with VM_encoding and ends with 2)
vm_run2[vm_run2 == "NULL"] <- NA #change all the "NULL" values to NA
vm_run2 <- vm_run2[, colSums(is.na(vm_run2)) != nrow(vm_run2)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime) 

#note: sometimes E-prime generates LongFixation1.OnsetTime instead of LongFixation.OnsetTime. To account for this: 
if(any(names(vm_run2) == "LongFixation1.OnsetTime")){
  names(vm_run2)[names(vm_run2) == "LongFixation1.OnsetTime"] <- "LongFixation.OnsetTime"
}


######## create a subset of the vm_recog task
recog <- subset(merged, grepl(pattern = "^VM_recog", merged$ExperimentName)) #create a subset of recognition task (experiment name starts with VM_recog)
recog[recog == "NULL"] <- NA #change all the "NULL" values to NA
recog <- recog[, colSums(is.na(recog)) != nrow(recog)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime) 

#note: sometimes E-prime generates LongFixation1.OnsetTime instead of LongFixation.OnsetTime. To account for this:
if(any(names(recog) == "LongFixation1.OnsetTime")){
  names(recog)[names(recog) == "LongFixation1.OnsetTime"] <- "LongFixation.OnsetTime"
}


######## create a subset of run1 of the EFN-back task
efn_run1 <- subset(merged, grepl(pattern = "^EFNBACK", merged$ExperimentName) & grepl(pattern = "1$", merged$ExperimentName)) #create a subset of Run 1 of EFN-BACK task (experiment name starts with EFNBACK and ends with 1)
efn_run1[efn_run1 == "NULL"] <- NA #change all the "NULL" values to NA
efn_run1 <- efn_run1[, colSums(is.na(efn_run1)) != nrow(efn_run1)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime)


######## create a subset of run2 of the EFN-back task
efn_run2 <- subset(merged, grepl(pattern = "^EFNBACK", merged$ExperimentName) & grepl(pattern = "2$", merged$ExperimentName)) #create a subset of Run 2 of EFN-BACK task (experiment name starts with EFNBACK and ends with 2)
efn_run2[efn_run2 == "NULL"] <- NA #change all the "NULL" values to NA
efn_run2 <- efn_run2[, colSums(is.na(efn_run2)) != nrow(efn_run2)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime)


######## create a subset of run1 of the False Belief task
fb_run1 <- subset(merged, grepl(pattern = "^FalseBelief", merged$ExperimentName) & grepl(pattern = "1$", merged$ExperimentName)) #create a subset of Run 1 of false belief task (experiment name starts with FalseBelief and ends with 1)
fb_run1[fb_run1 == "NULL"] <- NA #change all the "NULL" values to NA
fb_run1 <- fb_run1[, colSums(is.na(fb_run1)) != nrow(fb_run1)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime)


######## create a subset of run2 of the False Belief task
fb_run2 <- subset(merged, grepl(pattern = "^FalseBelief", merged$ExperimentName) & grepl(pattern = "2$", merged$ExperimentName)) #create a subset of Run 2 of false belief task (experiment name starts with FalseBelief and ends with 1)
fb_run2[fb_run2 == "NULL"] <- NA #change all the "NULL" values to NA
fb_run2 <- fb_run2[, colSums(is.na(fb_run2)) != nrow(fb_run2)] #if all rows of a column only contain NA, then remove this column (these are useless variables generated by E-prime)



################################### CREATING OUTPUT ##############################

#Create a txt file with each subset created above for each run of each task. File names are in the format of task_run_ID_TP.txt. 

write.table(vm_run1, file.path(paste0(BEH_DIR, '/VM/VM_Encoding/', id, '_TP', TP, '/vm_run1_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")
write.table(vm_run2, file.path(paste0(BEH_DIR, '/VM/VM_Encoding/', id, '_TP', TP, '/vm_run2_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")
write.table(recog, file.path(paste0(BEH_DIR, '/VM/VM_Recog/', id, '_TP', TP, '/recog_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")
write.table(efn_run1, file.path(paste0(BEH_DIR, '/EFN_BACK/', id, '_TP', TP, '/efn_run1_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")
write.table(efn_run2, file.path(paste0(BEH_DIR, '/EFN_BACK/', id, '_TP', TP, '/efn_run2_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")
write.table(fb_run1, file.path(paste0(BEH_DIR, '/FB/', id, '_TP', TP, '/fb_run1_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")
write.table(fb_run2, file.path(paste0(BEH_DIR, '/FB/', id, '_TP', TP, '/fb_run2_', id, '_TP', TP, '.txt')), row.names=FALSE, col.names = TRUE, sep = "\t")

